from pyspark.sql import SparkSession
from dbx_utils.logging import getLogger  # your custom logger


def ingest_setup(
    spark: SparkSession,
    catalog: str,
    schema: str,
    table: str,
) -> str:
    """
    Create (if not exists) the API configuration table that stores:
      - endpoint: string
      - params: map<string,string>
      - job_settings: map<string,string>

    This table will be used to define which API endpoints should be ingested.

    The setup only has to run once in total and doesn't need to run every job.

    Returns the full table name (catalog.schema.table).
    """
    logger = getLogger(__name__)
    full_table_name = f"{catalog}.{schema}.{table}"

    try:
        logger.info(f"Starting ingest setup for table '{full_table_name}'.")

        # Create catalog & schema (Unity Catalog safe operations)
        spark.sql(f"CREATE CATALOG IF NOT EXISTS {catalog}")
        spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{schema}")

        # If the table already exists, tell the user explicitly and exit.
        if spark.catalog.tableExists(full_table_name):
            logger.info(
                f"API config table '{full_table_name}' already exists. "
                f"No changes were made. You can safely reuse this table."
            )
            return full_table_name

        # Table does not exist yet: create the flexible config table
        spark.sql(f"""
        CREATE TABLE {full_table_name} (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
          endpoint STRING,
          params MAP<STRING, STRING>,
          job_settings MAP<STRING, STRING>
        )
        USING DELTA
        """)

        logger.info(f"Created new API config table '{full_table_name}'.")
        return full_table_name

    except Exception as e:
        logger.error(
            f"Failed to set up API config table '{full_table_name}': {e}",
            exc_info=True,
        )
        # Re-raise so the job/notebook fails loudly instead of silently
        raise
